/**
 * Mock product data for local development / staging before DB is seeded.
 * Images: Unsplash stable photo IDs (same ones used in FasoLocalUpdate/src/lib/data.js).
 * Replace with real Prisma queries once DB is seeded (see IMPLEMENTATION_PLAN.md Task 4).
 */
import { Product } from '@/types/product';

// Using Picsum Photos (seed-based) for guaranteed reliability.
// Same seed always returns the same image — swap for real product photos
// when vendors upload them via Supabase Storage (Phase 3).
function img(seed: string) {
  return `https://picsum.photos/seed/${seed}/600/600`;
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Miel Pur de Ouagadougou',
    slug: 'miel-pur-ouagadougou',
    description: 'Miel 100% naturel récolté par des apiculteurs formés aux techniques modernes. Non pasteurisé, sans additifs ni colorants. Riche en enzymes et antioxydants.',
    shortDescription: 'Miel pur non pasteurisé, récolte artisanale. 500g.',
    price: 3500,
    compareAtPrice: 4500,
    currency: 'XOF',
    category: 'agroalimentaire',
    tags: ['miel', 'naturel', 'bio'],
    stock: 42,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    weight: 500,
    origin: 'Ouagadougou',
    producer: { id: 'p1', name: 'Apiculteurs du Centre', location: 'Ouagadougou' },
    images: [{ id: '1a', url: img('miel-ouagadougou'), alt: 'Miel Pur de Ouagadougou', isPrimary: true }],
    ratings: { average: 4.8, count: 124 },
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Beurre de Karité Naturel',
    slug: 'beurre-karite-naturel',
    description: 'Beurre de karité pur extrait à froid selon les techniques traditionnelles burkinabè. Non raffiné, sans ajout chimique. Certifié biologique. Hydrate et nourrit profondément la peau et les cheveux.',
    shortDescription: 'Karité pur extrait à froid, certifié bio. 250g.',
    price: 2200,
    currency: 'XOF',
    category: 'cosmetiques',
    tags: ['karité', 'bio', 'hydratant', 'naturel'],
    stock: 80,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    weight: 250,
    origin: 'Ouagadougou',
    producer: { id: 'p2', name: 'Coopérative Wend-Panga', location: 'Ouagadougou' },
    images: [{ id: '2a', url: img('karite-beurre'), alt: 'Beurre de Karité', isPrimary: true }],
    ratings: { average: 4.9, count: 89 },
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    name: 'Faso Dan Fani (2 mètres)',
    slug: 'faso-dan-fani-2m',
    description: 'Tissu traditionnel du Burkina Faso tissé à la main sur un métier à tisser manuel. Motifs géométriques authentiques, teintures naturelles. Chaque pièce est unique et porte l\'héritage des tisserands de Koudougou.',
    shortDescription: 'Tissu traditionnel tissé à la main, motifs authentiques. 2m.',
    price: 6500,
    currency: 'XOF',
    category: 'textiles',
    tags: ['faso dan fani', 'tissage', 'artisanat', 'textile'],
    stock: 15,
    isAvailable: true,
    isFeatured: true,
    isNew: true,
    weight: 400,
    origin: 'Koudougou',
    producer: { id: 'p3', name: 'Tisserands de Koudougou', location: 'Koudougou' },
    images: [{ id: '3a', url: img('faso-dan-fani-textile'), alt: 'Faso Dan Fani', isPrimary: true }],
    ratings: { average: 4.7, count: 56 },
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '4',
    name: "Riz Local Grains d'Or",
    slug: 'riz-local-grains-or',
    description: "Riz blanc parfumé produit dans la vallée du Sourou, grenier à riz du Burkina Faso. Grain long, texture parfaite à la cuisson. Cultivé sans pesticides chimiques par les riziculteurs locaux.",
    shortDescription: 'Riz blanc parfumé, vallée du Sourou. 1kg.',
    price: 1800,
    currency: 'XOF',
    category: 'cereales-farines',
    tags: ['riz', 'céréale', 'local', 'sourou'],
    stock: 200,
    isAvailable: true,
    isFeatured: false,
    isNew: false,
    weight: 1000,
    origin: 'Sourou',
    producer: { id: 'p4', name: 'Riziculteurs du Sourou', location: 'Sourou' },
    images: [{ id: '4a', url: img('riz-local-sourou'), alt: 'Riz Local', isPrimary: true }],
    ratings: { average: 4.6, count: 203 },
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: '5',
    name: 'Savon Moringa Bio',
    slug: 'savon-moringa-bio',
    description: 'Savon artisanal enrichi en huile de moringa et miel de la région de Ziniaré. Sans sulfates ni parabènes. Convient aux peaux sensibles. Fabriqué à la main par les femmes de la coopérative.',
    shortDescription: 'Savon artisanal moringa & miel, sans sulfates. 120g.',
    price: 1200,
    compareAtPrice: 1600,
    currency: 'XOF',
    category: 'cosmetiques',
    tags: ['savon', 'moringa', 'artisanal', 'naturel'],
    stock: 67,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    weight: 120,
    origin: 'Ziniaré',
    producer: { id: 'p5', name: 'Femmes de Ziniaré', location: 'Ziniaré' },
    images: [{ id: '5a', url: img('savon-moringa-bio'), alt: 'Savon Moringa Bio', isPrimary: true }],
    ratings: { average: 4.8, count: 72 },
    createdAt: '2024-01-25T00:00:00Z',
    updatedAt: '2024-01-25T00:00:00Z',
  },
  {
    id: '6',
    name: 'Chapeau de Saponé',
    slug: 'chapeau-sapone',
    description: "Chapeau emblématique fabriqué à la main à Saponé. Paille naturelle tressée avec soin par des artisans certifiés. Labellisé \"Norme Burkinabè\". Protection solaire efficace, symbole de l'artisanat national.",
    shortDescription: 'Chapeau paille artisanal, labellisé NBF. Fait à Saponé.',
    price: 4000,
    currency: 'XOF',
    category: 'artisanat',
    tags: ['chapeau', 'paille', 'artisanat', 'saponé'],
    stock: 25,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    weight: 200,
    origin: 'Saponé',
    producer: { id: 'p6', name: 'Artisans de Saponé', location: 'Saponé' },
    images: [{ id: '6a', url: img('chapeau-sapone-burkina'), alt: 'Chapeau de Saponé', isPrimary: true }],
    ratings: { average: 4.9, count: 41 },
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-02-05T00:00:00Z',
  },
  {
    id: '7',
    name: 'Sésame Blanc Premium',
    slug: 'sesame-blanc-premium',
    description: 'Sésame blanc de qualité export cultivé dans la région Est du Burkina Faso. Riche en protéines, calcium et acides gras essentiels. Trié et nettoyé à la main. Idéal pour la cuisine et la cosmétique.',
    shortDescription: 'Sésame blanc export, région Est. 500g.',
    price: 2800,
    currency: 'XOF',
    category: 'cereales-farines',
    tags: ['sésame', 'céréale', 'protéines', 'export'],
    stock: 150,
    isAvailable: true,
    isFeatured: false,
    isNew: true,
    weight: 500,
    origin: "Fada N'Gourma",
    producer: { id: 'p7', name: 'Producteurs Est-Burkina', location: "Fada N'Gourma" },
    images: [{ id: '7a', url: img('sesame-blanc-burkina'), alt: 'Sésame Blanc', isPrimary: true }],
    ratings: { average: 4.5, count: 38 },
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-02-10T00:00:00Z',
  },
  {
    id: '8',
    name: 'Tisane Moringa & Citron',
    slug: 'tisane-moringa-citron',
    description: 'Mélange de feuilles de moringa séchées et de zeste de citron bio du Burkina. Riche en vitamines A, C et fer. Boîte de 20 sachets infusettes. Sans théine, idéale le soir.',
    shortDescription: 'Tisane moringa & citron bio. 20 sachets.',
    price: 950,
    currency: 'XOF',
    category: 'sante-bien-etre',
    tags: ['tisane', 'moringa', 'bio', 'vitamine'],
    stock: 95,
    isAvailable: true,
    isFeatured: false,
    isNew: true,
    weight: 40,
    origin: 'Ouagadougou',
    producer: { id: 'p8', name: 'Herboristerie Laafi', location: 'Ouagadougou' },
    images: [{ id: '8a', url: img('tisane-moringa-citron'), alt: 'Tisane Moringa Citron', isPrimary: true }],
    ratings: { average: 4.7, count: 61 },
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: '9',
    name: 'Huile de Sésame Grillé',
    slug: 'huile-sesame-grille',
    description: 'Huile pure obtenue par pression à froid de sésame grillé artisanalement. Arôme intense et saveur riche. Bouteille en verre 500ml. Idéale pour assaisonner les plats ou comme huile de massage.',
    shortDescription: 'Huile sésame grillé, pression à froid. 500ml.',
    price: 3200,
    currency: 'XOF',
    category: 'agroalimentaire',
    tags: ['huile', 'sésame', 'artisanal', 'cuisine'],
    stock: 55,
    isAvailable: true,
    isFeatured: false,
    isNew: false,
    weight: 500,
    origin: 'Ouagadougou',
    producer: { id: 'p9', name: 'Huilerie Artisanale Yennenga', location: 'Ouagadougou' },
    images: [{ id: '9a', url: img('huile-sesame-grille'), alt: 'Huile de Sésame', isPrimary: true }],
    ratings: { average: 4.6, count: 28 },
    createdAt: '2024-01-30T00:00:00Z',
    updatedAt: '2024-01-30T00:00:00Z',
  },
  {
    id: '10',
    name: 'Poudre de Baobab',
    slug: 'poudre-baobab',
    description: "Poudre de pulpe de baobab séchée. Très riche en vitamine C (6× plus que l'orange), calcium et fibres alimentaires. Idéale dans smoothies, yaourts ou jus de fruits. Sachet 200g hermétique.",
    shortDescription: 'Poudre de baobab riche en vitamine C. 200g.',
    price: 1600,
    currency: 'XOF',
    category: 'sante-bien-etre',
    tags: ['baobab', 'vitamine C', 'superfood', 'bio'],
    stock: 110,
    isAvailable: true,
    isFeatured: true,
    isNew: false,
    weight: 200,
    origin: 'Dori',
    producer: { id: 'p10', name: 'Collectif Femmes du Sahel', location: 'Dori' },
    images: [{ id: '10a', url: img('poudre-baobab-sahel'), alt: 'Poudre de Baobab', isPrimary: true }],
    ratings: { average: 4.8, count: 85 },
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: '11',
    name: 'Soumbala Traditionnel',
    slug: 'soumbala-traditionnel',
    description: "Condiment fermenté traditionnel à base de graines de néré. Indispensable de la cuisine burkinabè et ouest-africaine. Fabriqué selon des recettes ancestrales transmises de mère en fille. Sachet 200g.",
    shortDescription: 'Soumbala traditionnel au néré, recette ancestrale. 200g.',
    price: 800,
    currency: 'XOF',
    category: 'epices-condiments',
    tags: ['soumbala', 'épice', 'condiment', 'traditionnel'],
    stock: 200,
    isAvailable: true,
    isFeatured: false,
    isNew: false,
    weight: 200,
    origin: 'Bobo-Dioulasso',
    producer: { id: 'p11', name: 'Productrices de Bobo-Dioulasso', location: 'Bobo-Dioulasso' },
    images: [{ id: '11a', url: img('soumbala-nere-bobo'), alt: 'Soumbala Traditionnel', isPrimary: true }],
    ratings: { average: 4.4, count: 92 },
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-08T00:00:00Z',
  },
  {
    id: '12',
    name: 'Bracelet en Bronze de Tiébélé',
    slug: 'bracelet-bronze-tiebele',
    description: "Bracelet artisanal fabriqué selon la technique ancestrale kassena de fonte à la cire perdue. Chaque pièce est coulée individuellement par un maître artisan — pièce unique. Motifs géométriques kasséna.",
    shortDescription: 'Bronze kassena, fonte à la cire perdue. Pièce unique.',
    price: 5500,
    compareAtPrice: 7000,
    currency: 'XOF',
    category: 'artisanat',
    tags: ['bronze', 'bijou', 'kassena', 'artisanat'],
    stock: 18,
    isAvailable: true,
    isFeatured: true,
    isNew: true,
    weight: 85,
    origin: 'Tiébélé',
    producer: { id: 'p12', name: 'Bijoutiers Kassena', location: 'Tiébélé' },
    images: [{ id: '12a', url: img('bracelet-bronze-tiebele'), alt: 'Bracelet Bronze Tiébélé', isPrimary: true }],
    ratings: { average: 4.9, count: 34 },
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
];

export const FEATURED_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.isFeatured);
export const NEW_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.isNew);

export function getProductBySlug(slug: string): Product | undefined {
  return MOCK_PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (!category || category === 'all') return MOCK_PRODUCTS;
  return MOCK_PRODUCTS.filter((p) => p.category === category);
}
